### ISSUE TITLE
Errors when building

### ISSUE THREAD

**Issue by ScribbleNerd** [Seo-Rii/electron-acrylic-window#38] opened 2020-10-28 01:22 UTC
When running `npm i electron-acrylic-window`, I get the following errors:
```
D:\Coding\Node.js Projects\Electron\Electron Webserver v2>npm i electron-acrylic-window
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported

> win32-displayconfig@0.1.0 install D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig
> npm run rebuild


> win32-displayconfig@0.1.0 rebuild D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig
> node-gyp rebuild


D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  win32-displayconfig.cc
  win_delay_load_hook.cc
..\win32-displayconfig.cc(478): error C2039: 'cloneGroupId': is not a member of 'DISPLAYCONFIG_PATH_SOURCE_INFO' [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displa
yconfig.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\wingdi.h(2921): note: see declaration of 'DISPLAYCONFIG_PATH_SOURCE_INFO'
..\win32-displayconfig.cc(478): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v 
cxproj]
..\win32-displayconfig.cc(478): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(478): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(478): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco 
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(478): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon 
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(478): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(479): error C2039: 'sourceModeInfoIdx': is not a member of 'DISPLAYCONFIG_PATH_SOURCE_INFO' [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_d 
isplayconfig.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\wingdi.h(2921): note: see declaration of 'DISPLAYCONFIG_PATH_SOURCE_INFO'
..\win32-displayconfig.cc(479): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v 
cxproj]
..\win32-displayconfig.cc(479): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(479): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(479): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(479): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon 
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(479): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(518): error C2065: 'DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_WIRED': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_di 
splayconfig.vcxproj]
..\win32-displayconfig.cc(518): error C2131: expression did not evaluate to a constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
  ..\win32-displayconfig.cc(518): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\win32-displayconfig.cc(518): note: see usage of 'DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_WIRED'
..\win32-displayconfig.cc(520): error C2065: 'DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_VIRTUAL': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_ 
displayconfig.vcxproj]
..\win32-displayconfig.cc(520): error C2131: expression did not evaluate to a constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
  ..\win32-displayconfig.cc(520): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\win32-displayconfig.cc(520): note: see usage of 'DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_VIRTUAL'
..\win32-displayconfig.cc(518): error C2051: case expression not constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
..\win32-displayconfig.cc(520): error C2051: case expression not constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
..\win32-displayconfig.cc(594): error C2039: 'desktopModeInfoIdx': is not a member of 'DISPLAYCONFIG_PATH_TARGET_INFO' [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_ 
displayconfig.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\wingdi.h(2935): note: see declaration of 'DISPLAYCONFIG_PATH_TARGET_INFO'
..\win32-displayconfig.cc(594): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v 
cxproj]
..\win32-displayconfig.cc(594): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(594): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(594): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco 
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(594): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon 
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(594): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(595): error C2039: 'targetModeInfoIdx': is not a member of 'DISPLAYCONFIG_PATH_TARGET_INFO' [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_d 
isplayconfig.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\wingdi.h(2935): note: see declaration of 'DISPLAYCONFIG_PATH_TARGET_INFO'
..\win32-displayconfig.cc(595): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v 
cxproj]
..\win32-displayconfig.cc(595): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(595): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(595): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco 
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(595): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(595): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(605): error C2065: 'DISPLAYCONFIG_PATH_SUPPORT_VIRTUAL_MODE': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayco 
nfig.vcxproj]
..\win32-displayconfig.cc(606): error C3536: 'supportsVirtualMode': cannot be used before it is initialized [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconf 
ig.vcxproj]
..\win32-displayconfig.cc(666): error C2065: 'DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displa 
yconfig.vcxproj]
..\win32-displayconfig.cc(666): error C2131: expression did not evaluate to a constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
  ..\win32-displayconfig.cc(666): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\win32-displayconfig.cc(666): note: see usage of 'DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE'
..\win32-displayconfig.cc(666): error C2051: case expression not constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
..\win32-displayconfig.cc(698): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win 
32_displayconfig.vcxproj]
..\win32-displayconfig.cc(698): error C2143: syntax error: missing ',' before '&' [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
..\win32-displayconfig.cc(700): error C2065: 'imageInfo': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
..\win32-displayconfig.cc(700): error C2228: left of '.PathSourceSize' must have class/struct/union [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxpr 
oj]
  ..\win32-displayconfig.cc(700): note: type is 'unknown-type'
..\win32-displayconfig.cc(700): error C2660: 'ConvertPointL': function does not take 1 arguments [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj] 
..\win32-displayconfig.cc(700): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v
cxproj]
..\win32-displayconfig.cc(700): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(700): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(700): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco 
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(700): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon 
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(700): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(701): error C2065: 'imageInfo': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
..\win32-displayconfig.cc(701): error C2228: left of '.DesktopImageRegion' must have class/struct/union [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v 
cxproj]
  ..\win32-displayconfig.cc(701): note: type is 'unknown-type'
..\win32-displayconfig.cc(701): error C2660: 'ConvertRectL': function does not take 1 arguments [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]  
..\win32-displayconfig.cc(701): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v
cxproj]
..\win32-displayconfig.cc(701): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(701): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(701): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco 
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(701): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon 
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(701): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(702): error C2065: 'imageInfo': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
..\win32-displayconfig.cc(702): error C2228: left of '.DesktopImageClip' must have class/struct/union [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcx 
proj]
  ..\win32-displayconfig.cc(702): note: type is 'unknown-type'
..\win32-displayconfig.cc(702): error C2660: 'ConvertRectL': function does not take 1 arguments [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]  
..\win32-displayconfig.cc(702): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v 
cxproj]
..\win32-displayconfig.cc(702): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(702): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(702): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco 
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(702): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(702): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(719): error C2065: 'DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE': undeclared identifier [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displa 
yconfig.vcxproj]
..\win32-displayconfig.cc(719): error C2131: expression did not evaluate to a constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
  ..\win32-displayconfig.cc(719): note: failure was caused by non-constant arguments or reference to a non-constant symbol
  ..\win32-displayconfig.cc(719): note: see usage of 'DISPLAYCONFIG_MODE_INFO_TYPE_DESKTOP_IMAGE'
..\win32-displayconfig.cc(720): error C2039: 'desktopImageInfo': is not a member of 'DISPLAYCONFIG_MODE_INFO' [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayco 
nfig.vcxproj]
  C:\Program Files (x86)\Windows Kits\8.1\Include\um\wingdi.h(2907): note: see declaration of 'DISPLAYCONFIG_MODE_INFO'
..\win32-displayconfig.cc(720): error C2660: 'ConvertDesktopImageInfo': function does not take 1 arguments [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfi 
g.vcxproj]
..\win32-displayconfig.cc(720): error C2672: 'Napi::Object::Set': no matching overloaded function found [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.v
cxproj]
..\win32-displayconfig.cc(720): error C2780: 'void Napi::Object::Set(uint32_t,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig 
\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(702): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(720): error C2780: 'void Napi::Object::Set(const std::string &,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-di 
splayconfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(665): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(720): error C2780: 'void Napi::Object::Set(const char *,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayco 
nfig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(658): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(720): error C2780: 'void Napi::Object::Set(Napi::Value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displaycon 
fig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(651): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(720): error C2780: 'void Napi::Object::Set(napi_value,const ValueType &)': expects 2 arguments - 1 provided [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconf 
ig\build\win32_displayconfig.vcxproj]
  D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\node-addon-api\napi.h(644): note: see declaration of 'Napi::Object::Set'
..\win32-displayconfig.cc(719): error C2051: case expression not constant [D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig\build\win32_displayconfig.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Coding\Node.js Projects\Electron\Electron Webserver v2\node_modules\win32-displayconfig
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! win32-displayconfig@0.1.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the win32-displayconfig@0.1.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\benji\AppData\Roaming\npm-cache\_logs\2020-10-28T01_20_54_305Z-debug.log
npm WARN electrohttp@1.0.0 No description
npm WARN electrohttp@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! win32-displayconfig@0.1.0 install: `npm run rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the win32-displayconfig@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\benji\AppData\Roaming\npm-cache\_logs\2020-10-28T01_20_54_595Z-debug.log
```

How can I fix this?

**Comment by Seo-Rii** [comment] 2020-10-28 02:20
Duplicate of #31.
Remove Windows 8.1 SDK, install 10 SDK, and try again.

**Comment by tscpp** [comment] 2020-10-29 11:33
Duplicates should be closed.

**Closed** 2020-10-29 15:09 UTC

**Comment by ScribbleNerd** [comment] 2020-10-30 13:38
> Duplicate of #31.
> Remove Windows 8.1 SDK, install 10 SDK, and try again.

I'm kind of new to build tools and stuff, so how would I do this?

**Comment by Seo-Rii** [comment] 2020-10-30 15:40
Try ```npm install --global --production windows-build-tools --vs2015``` and ```npm config set msvs_version 2015 –global```.
