### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by meisme-dev** [Seo-Rii/electron-acrylic-window#49] opened 2021-01-10 15:23 UTC
I have installed all the dependencies for electron-acrylic-window (windows-build-tools) and it won't install when I run ` npm i electron-acrylic-window --save`. Here are the logs: 

[2021-01-10T15_20_26_542Z-debug.log](https://github.com/Seo-Rii/electron-acrylic-window/files/5792797/2021-01-10T15_20_26_542Z-debug.log)

**EDIT:** Ran the command in CMD instead of PowerShell, different errors.

[2021-01-10T15_30_13_035Z-debug.log](https://github.com/Seo-Rii/electron-acrylic-window/files/5792811/2021-01-10T15_30_13_035Z-debug.log)

**Comment by Seo-Rii** [comment] 2021-01-11 10:41
Duplicate of #46. Please use version 0.4.7 before the modifications are applied.

**Closed by Seo-Rii** 2021-01-11 10:41 UTC

**Comment by Seo-Rii** [comment] 2021-01-11 16:33
@meisme-dev It has resolved on v0.5.5!
